### ISSUE TITLE
Implement master ban list on HTTPS masters

### ISSUE THREAD

**Issue by Rei-Tw** [heinrich5991/twmaster-collect#2]
Hi,

As I've heard about, HTTPS masters seems to not have any "master ban" feature.
It would be great if DDNet could ban based on the IP for example, or even giving some regex or strings so that you can prevent fake DDNet servers as an example.

**Comment by heinrich5991** [comment]
Wrong repository, it currently lives at https://github.com/heinrich5991/libtw2/tree/9fbebeb34c7f56741307cd1685dbcfcc5b2a5929/stats_browser.
